### ISSUE TITLE
Test failure: test encoder::compression::deflate::tests::test_deflate

### ISSUE THREAD

**Issue by emixa-d** [image-rs/image-tiff#169]
When building image-tiff (vesion 0.7.2), I get the following error:

```
running 8 tests
test encoder::compression::packbits::tests::test_packbits_rept ... ok
test encoder::compression::packbits::tests::test_packbits_large_rept_nonrept ... ok
test decoder::stream::test::test_packbits ... ok
test encoder::compression::packbits::tests::test_packbits_single_byte ... ok
test encoder::compression::packbits::tests::test_packbits ... ok
test encoder::compression::uncompressed::tests::test_no_compression ... ok
test encoder::compression::lzw::tests::test_lzw ... ok
test encoder::compression::deflate::tests::test_deflate ... FAILED

failures:

---- encoder::compression::deflate::tests::test_deflate stdout ----
thread 'encoder::compression::deflate::tests::test_deflate' panicked at 'assertion failed: `(left == right)`
  left: `[120, 156, 21, 199, 209, 13, 128, 32, 12, 4, 208, 85, 110, 2, 167, 113, 129, 166, 65, 218, 40, 212, 244, 208, 249, 129, 228, 253, 188, 211, 156, 88, 4, 28, 233, 189, 226, 138, 132, 90, 209, 123, 231, 151, 244, 248, 8, 141, 246, 102, 33, 61, 58, 228, 169, 145, 62, 172, 241, 152, 185, 112, 23, 19]`,
 right: `[120, 156, 21, 199, 209, 13, 128, 32, 12, 5, 192, 85, 222, 4, 78, 227, 2, 77, 131, 180, 81, 40, 233, 3, 230, 87, 147, 251, 185, 211, 156, 248, 8, 56, 211, 123, 197, 21, 9, 181, 162, 247, 159, 45, 233, 177, 8, 141, 54, 178, 144, 30, 29, 242, 212, 72, 159, 214, 120, 188, 185, 112, 23, 19]`', src/encoder/compression/deflate.rs:81:9
stack backtrace:
   0:     0x7ffff7e3361c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7767eb774a4d4f42
   1:     0x7ffff7ec4bfc - core::fmt::write::hf3fb1fb91b38bb59
   2:     0x7ffff7e01bd5 - <unknown>
   3:     0x7ffff7e151bb - <unknown>
   4:     0x7ffff7e14d61 - <unknown>
   5:     0x7ffff7e1598b - std::panicking::rust_panic_with_hook::h19ec2b337ecb8872
   6:     0x7ffff7e34450 - <unknown>
   7:     0x7ffff7e33744 - <unknown>
   8:     0x7ffff7e15402 - rust_begin_unwind
   9:     0x7ffff7df5681 - core::panicking::panic_fmt::h964c785332841a13
  10:     0x7ffff7ea87f8 - core::panicking::assert_failed_inner::h45014c2f24de47a0
  11:     0x55555555836f - core::panicking::assert_failed::h71b70f1e561685f9
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/panicking.rs:138:5
  12:     0x55555555bcb2 - lib::encoder::compression::deflate::tests::test_deflate::h70bb6a3f73b96997
                               at /tmp/guix-build-rust-tiff-0.7.2.drv-0/tiff-0.7.2/src/encoder/compression/deflate.rs:81:9
  13:     0x7ffff7f58293 - <unknown>
  14:     0x7ffff7f5845b - <unknown>
  15:     0x7ffff7f6df75 - <unknown>
  16:     0x7ffff7f66d0f - <unknown>
  17:     0x7ffff7e250e3 - <unknown>
  18:     0x7ffff7b7cd7e - <unknown>
  19:     0x7ffff7c8aeff - clone
  20:                0x0 - <unknown>


failures:
    encoder::compression::deflate::tests::test_deflate

test result: FAILED. 7 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by emixa-d** [comment]
It also happens on 0.7.3.

**Comment by emixa-d** [comment]
Some additional information: rust-flate2 is (locally) being compiled with the "zlib" feature, to use the zlib library that is installed anyway instead of adding a bunch of new dependencies.

**Comment by 197g** [comment]
I don't think this is relevant anymore? We have CI testing across architectures and both endianess systems and nothing triggered a test failure on this in recent memory. If it is reproducible on `0.10` then I'd love to find out more about the system environment that's being used since I don't imagine it is the flate code.
